In [8]:
# import torch

In [9]:
# x = torch.randn(2, 3)

In [11]:
# torch.cat((x,x),1)
# torch.cat([x,x],1)

tensor([[ 1.0491,  1.3108, -0.3069,  1.0491,  1.3108, -0.3069],
        [-1.0276,  1.6398,  0.3385, -1.0276,  1.6398,  0.3385]])

TypeError: cat() received an invalid combination of arguments - got (Tensor, Tensor, int), but expected one of:
 * (tuple of Tensors tensors, name dim, Tensor out)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, int)
 * (tuple of Tensors tensors, int dim, Tensor out)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, int)


In [6]:
input1 = torch.randn(100, 128)
input2 = torch.randn(100, 128)
output = torch.nn.functional.cosine_similarity(input1, input2)
print(output)
cos = torch.nn.CosineSimilarity(dim=1, eps=1e-6)
output = cos(input1, input2)
output

tensor([-0.0777, -0.0970,  0.0581, -0.0089,  0.0076,  0.0300, -0.0102,  0.0492,
         0.0349,  0.0557, -0.0623,  0.1101,  0.0980,  0.1694, -0.0950, -0.0547,
        -0.0721,  0.0201,  0.0044,  0.0868, -0.0568, -0.0372, -0.0362, -0.0314,
         0.1946,  0.0224,  0.1003,  0.0059,  0.0448, -0.0282,  0.0414, -0.0589,
        -0.0151,  0.0847, -0.0529, -0.0635,  0.1430,  0.0427, -0.0659, -0.0944,
        -0.1080,  0.1134,  0.0105,  0.0405,  0.0457,  0.0243, -0.0531, -0.1876,
        -0.0543,  0.0018,  0.0488, -0.0330,  0.1080, -0.0170,  0.0924,  0.0433,
        -0.0776, -0.0542,  0.0586,  0.0806,  0.1500, -0.0913,  0.1289,  0.0999,
         0.1060, -0.0098, -0.0446,  0.0665, -0.0005,  0.0773, -0.0710, -0.0408,
        -0.0620,  0.0172,  0.0193,  0.0892,  0.0225,  0.0115,  0.0964,  0.0518,
        -0.0206, -0.0354, -0.0006, -0.0388,  0.0295, -0.1801, -0.0106, -0.0452,
        -0.0838, -0.0948,  0.1395,  0.2608, -0.0447, -0.0062,  0.0268,  0.0071,
         0.0570,  0.0155,  0.0209, -0.04

tensor([-0.0777, -0.0970,  0.0581, -0.0089,  0.0076,  0.0300, -0.0102,  0.0492,
         0.0349,  0.0557, -0.0623,  0.1101,  0.0980,  0.1694, -0.0950, -0.0547,
        -0.0721,  0.0201,  0.0044,  0.0868, -0.0568, -0.0372, -0.0362, -0.0314,
         0.1946,  0.0224,  0.1003,  0.0059,  0.0448, -0.0282,  0.0414, -0.0589,
        -0.0151,  0.0847, -0.0529, -0.0635,  0.1430,  0.0427, -0.0659, -0.0944,
        -0.1080,  0.1134,  0.0105,  0.0405,  0.0457,  0.0243, -0.0531, -0.1876,
        -0.0543,  0.0018,  0.0488, -0.0330,  0.1080, -0.0170,  0.0924,  0.0433,
        -0.0776, -0.0542,  0.0586,  0.0806,  0.1500, -0.0913,  0.1289,  0.0999,
         0.1060, -0.0098, -0.0446,  0.0665, -0.0005,  0.0773, -0.0710, -0.0408,
        -0.0620,  0.0172,  0.0193,  0.0892,  0.0225,  0.0115,  0.0964,  0.0518,
        -0.0206, -0.0354, -0.0006, -0.0388,  0.0295, -0.1801, -0.0106, -0.0452,
        -0.0838, -0.0948,  0.1395,  0.2608, -0.0447, -0.0062,  0.0268,  0.0071,
         0.0570,  0.0155,  0.0209, -0.04

In [4]:
input1 = torch.randn(100, 128)
input2 = torch.randn(100, 128)
cos = torch.nn.CosineSimilarity(dim=1, eps=1e-6)
output = cos(input1, input2)
output

tensor([ 0.2532,  0.1803,  0.0249,  0.0131, -0.0516, -0.0036, -0.0887,  0.0855,
        -0.1011, -0.0052, -0.1159,  0.0311, -0.1333, -0.1365,  0.0433, -0.0435,
         0.0068,  0.0291,  0.0442,  0.0453,  0.1120, -0.0947, -0.0289, -0.0597,
         0.0005, -0.0532, -0.0093,  0.0173, -0.0900,  0.0806,  0.1633,  0.1256,
         0.0219,  0.2469,  0.1581,  0.0248,  0.0227,  0.0527, -0.0426, -0.0387,
         0.1630,  0.1409,  0.0184, -0.0114, -0.2164, -0.0239, -0.1668,  0.0121,
         0.1230, -0.0469, -0.1112, -0.0297, -0.0266, -0.0177,  0.0300, -0.0027,
        -0.0275,  0.1194, -0.0010,  0.0534, -0.0461, -0.1345, -0.1804, -0.1094,
        -0.0512, -0.0718, -0.1513,  0.2292, -0.0711,  0.0994,  0.0310,  0.0493,
         0.0412, -0.0485,  0.0147, -0.0163,  0.0349,  0.0224,  0.0768,  0.0501,
         0.0782, -0.0880,  0.1491,  0.0736, -0.0296,  0.0977,  0.1150, -0.0092,
         0.0442, -0.0153,  0.0071,  0.0811, -0.0285,  0.0251, -0.0334,  0.1750,
         0.0948,  0.1309,  0.0327,  0.08

In [8]:
import math
import numpy as np
import torch


class TS_SS:
    
    def Cosine(self, vec1: torch.tensor, vec2: torch.tensor):
        return np.dot(vec1, vec2.T)/(np.linalg.norm(vec1) * np.linalg.norm(vec2))

    def VectorSize(self, vec: torch.tensor):
        return np.linalg.norm(vec)

    def Euclidean(self, vec1: torch.tensor, vec2: torch.tensor):
        return np.linalg.norm(vec1-vec2)

    def Theta(self, vec1: torch.tensor, vec2: torch.tensor):
        return np.arccos(self.Cosine(vec1, vec2)) + np.radians(10)

    def Triangle(self, vec1: torch.tensor, vec2: torch.tensor):
        theta = np.radians(self.Theta(vec1, vec2))
        return (self.VectorSize(vec1) * self.VectorSize(vec2) * np.sin(theta))/2

    def Magnitude_Difference(self, vec1: torch.tensor, vec2: torch.tensor):
        return abs(self.VectorSize(vec1) - self.VectorSize(vec2))

    def Sector(self, vec1: torch.tensor, vec2: torch.tensor):
        ED = self.Euclidean(vec1, vec2)
        MD = self.Magnitude_Difference(vec1, vec2)
        theta = self.Theta(vec1, vec2)
        return math.pi * (ED + MD)**2 * theta/360


    def __call__(self, vec1: torch.tensor, vec2: torch.tensor):
        return self.Triangle(vec1, vec2) * self.Sector(vec1, vec2)

In [47]:
class TS_SS:
    
    def Cosine(self, vec1: np.ndarray, vec2: np.ndarray):
        return np.dot(vec1, vec2.T)/(np.linalg.norm(vec1) * np.linalg.norm(vec2))

    def VectorSize(self, vec: np.ndarray):
        return np.linalg.norm(vec)

    def Euclidean(self, vec1: np.ndarray, vec2: np.ndarray):
        return np.linalg.norm(vec1-vec2)

    def Theta(self, vec1: np.ndarray, vec2: np.ndarray):
        return np.arccos(self.Cosine(vec1, vec2)) + np.radians(10)

    def Triangle(self, vec1: np.ndarray, vec2: np.ndarray):
        theta = np.radians(self.Theta(vec1, vec2))
        return (self.VectorSize(vec1) * self.VectorSize(vec2) * np.sin(theta))/2

    def Magnitude_Difference(self, vec1: np.ndarray, vec2: np.ndarray):
        return abs(self.VectorSize(vec1) - self.VectorSize(vec2))

    def Sector(self, vec1: np.ndarray, vec2: np.ndarray):
        ED = self.Euclidean(vec1, vec2)
        MD = self.Magnitude_Difference(vec1, vec2)
        theta = self.Theta(vec1, vec2)
        return math.pi * (ED + MD)**2 * theta/360


    def __call__(self, vec1: np.ndarray, vec2: np.ndarray):
        return self.Triangle(vec1, vec2) * self.Sector(vec1, vec2)

In [60]:
v1 = torch.rand(64,768)
v2 = torch.rand(64,768)

v1 = torch.tensor([[-3.3236,  0.8446],
        [ 3.5251, -4.3924],
        [-3.1383,  0.2581],
        [-3.0527,  0.2242],
        [-3.6991,  0.8463],
        [-2.3161, -0.4221],
        [-3.3808,  0.5008],
        [-3.8276,  0.1]])

v2 = torch.tensor([[ 0.9637, -2.0288],
        [-3.1887,  0.2983],
        [ 2.8996, -3.8029],
        [-3.4755,  0.6081],
        [-3.9159,  1.0350],
        [-3.6070,  0.7195],
        [-3.9225,  1.0456],
        [-2.9824,  0.1]])

v1 = torch.tensor([[ 0.9637, -2.0288],[-3.1887,  0.2983],[ 0.1, -2.0]])
v2 = torch.tensor([[ -0.9637, 2.0288],[-2.3161, -0.4221],[ 0.1, -2.0]])
similarity = TS_SS()
print(torch.tensor(similarity(v1,v2)))
torch.cosine_similarity(v1, v2, dim=1)

tensor([[0.1457, 0.1157, 0.0775],
        [0.0805, 0.0584, 0.1123],
        [0.1380, 0.1012, 0.0784]])


tensor([-1.0000,  0.9628,  1.0000])

In [55]:
v1.numpy()

array([[ 0.9637, -2.0288],
       [-3.1887,  0.2983]], dtype=float32)

In [1]:
import torch
import random
import numpy as np
import os

from tqdm import tqdm, trange
# torch.cuda.empty_cache()
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
from pytorch_pretrained_bert.optimization import BertAdam

In [2]:
from run_classifier import StanceProcessor, MrpcProcessor, logger, convert_examples_to_features,\
    set_optimizer_params_grad, copy_optimizer_params_to_model, accuracy, p_r_f1, tp_pcount_gcount, convert_claims_to_features, convert_pers_to_features

In [3]:
if torch.cuda.is_available():    

    # Tell PyTorch to use the GPU.    
    device = torch.device("cuda")
    n_gpu = torch.cuda.device_count()
    logger.info('There are %d GPU(s) available.' % (n_gpu))
    logger.info('We will use the GPU:')
    logger.info(torch.cuda.get_device_name(0))

# If not...
else:
    logger.info('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

06/18/2020 13:04:38 - INFO - run_classifier -   There are 1 GPU(s) available.
06/18/2020 13:04:38 - INFO - run_classifier -   We will use the GPU:
06/18/2020 13:04:38 - INFO - run_classifier -   GeForce GTX 1050 Ti


In [4]:
from transformers import BertTokenizer, AdamW, get_linear_schedule_with_warmup
from pytorch_pretrained_bert.modeling import BertForSequenceClassification, BertPreTrainedModel, BertModel, BertConfig
from torch.nn import BCEWithLogitsLoss, CosineEmbeddingLoss,CrossEntropyLoss, MSELoss

06/18/2020 13:04:39 - INFO - transformers.file_utils -   PyTorch version 1.4.0 available.
06/18/2020 13:04:41 - INFO - transformers.file_utils -   TensorFlow version 2.1.0 available.


In [5]:
class BertForConsistencyCueClassification(BertPreTrainedModel):
    def __init__(self, config, num_labels=2):
        super(BertForConsistencyCueClassification, self).__init__(config)
        self.num_labels = num_labels

        self.bert = BertModel(config)
        self.dropout = torch.nn.Dropout(config.hidden_dropout_prob)
        self.classifier = torch.nn.Linear(config.hidden_size*4+1, num_labels)
        self.classifier2 = torch.nn.Linear(config.hidden_size*4, num_labels)
        self.apply(self.init_bert_weights)
#         self.init_weights()

#     @add_start_docstrings_to_callable(BERT_INPUTS_DOCSTRING)
    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        token_type_ids=None,
        position_ids=None,
        head_mask=None,
        inputs_embeds=None,
        labels=None,
        input_ids2=None,
        attention_mask2=None,
        token_type_ids2=None,
        position_ids2=None,
        head_mask2=None,
        inputs_embeds2=None,
        labels2=None,
    ):
        r"""
        labels (:obj:`torch.LongTensor` of shape :obj:`(batch_size,)`, `optional`, defaults to :obj:`None`):
            Labels for computing the sequence classification/regression loss.
            Indices should be in :obj:`[0, ..., config.num_labels - 1]`.
            If :obj:`config.num_labels == 1` a regression loss is computed (Mean-Square loss),
            If :obj:`config.num_labels > 1` a classification loss is computed (Cross-Entropy).

    Returns:
        :obj:`tuple(torch.FloatTensor)` comprising various elements depending on the configuration (:class:`~transformers.BertConfig`) and inputs:
        loss (:obj:`torch.FloatTensor` of shape :obj:`(1,)`, `optional`, returned when :obj:`label` is provided):
            Classification (or regression if config.num_labels==1) loss.
        logits (:obj:`torch.FloatTensor` of shape :obj:`(batch_size, config.num_labels)`):
            Classification (or regression if config.num_labels==1) scores (before SoftMax).
        hidden_states (:obj:`tuple(torch.FloatTensor)`, `optional`, returned when ``config.output_hidden_states=True``):
            Tuple of :obj:`torch.FloatTensor` (one for the output of the embeddings + one for the output of each layer)
            of shape :obj:`(batch_size, sequence_length, hidden_size)`.

            Hidden-states of the model at the output of each layer plus the initial embedding outputs.
        attentions (:obj:`tuple(torch.FloatTensor)`, `optional`, returned when ``config.output_attentions=True``):
            Tuple of :obj:`torch.FloatTensor` (one for each layer) of shape
            :obj:`(batch_size, num_heads, sequence_length, sequence_length)`.

            Attentions weights after the attention softmax, used to compute the weighted average in the self-attention
            heads.

    Examples::

        from transformers import BertTokenizer, BertForSequenceClassification
        import torch

        tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
        model = BertForSequenceClassification.from_pretrained('bert-base-uncased')

        input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute", add_special_tokens=True)).unsqueeze(0)  # Batch size 1
        labels = torch.tensor([1]).unsqueeze(0)  # Batch size 1
        outputs = model(input_ids, labels=labels)

        loss, logits = outputs[:2]

        """

        _, outputs = self.bert(
            input_ids,
            attention_mask=attention_mask,
            token_type_ids=token_type_ids,
#             position_ids=position_ids,
#             head_mask=head_mask,
#             inputs_embeds=inputs_embeds,
        )

        _, outputs2 = self.bert(
            input_ids2,
            attention_mask=attention_mask2,
            token_type_ids=token_type_ids2,
#             position_ids=position_ids2,
#             head_mask=head_mask2,
#             inputs_embeds=inputs_embeds2,
        )

        pooled_output = outputs
        pooled_output2 = outputs2

        pooled_output = self.dropout(pooled_output)
        pooled_output2 = self.dropout(pooled_output2)
        
#         A series of different concatenations(concat(),|minus|,multiply, ...)
        final_output_cat = torch.cat((pooled_output, pooled_output2),1)
        final_output_minus = torch.abs(pooled_output-pooled_output2)
        final_output_mult = torch.mul(pooled_output, pooled_output2)
#         final_output_mimu = torch.cat((final_output_minus, final_output_mult),1)
#         final_output_camu = torch.cat((final_output_cat, final_output_mult),1)
#         final_output_cami = torch.cat((final_output_cat, final_output_minus),1)
        final_output_camimu = torch.cat((final_output_cat, final_output_minus, final_output_mult),1)
    
        cos_pooled_outputs = torch.cosine_similarity(pooled_output, pooled_output2, dim=1)
#         1
#         torch.Size([hidden_size*2, 768])
#         2
#         torch.Size([hidden_size, 768])
#         3
#         torch.Size([hidden_size, 768])
#         4
#         torch.Size([hidden_size*2, 768])
#         5
#         torch.Size([hidden_size*3, 768])
#         6
#         torch.Size([hidden_size*3, 768])
#         7
#         torch.Size([hidden_size*4, 768])
        
        batch_size = list(pooled_output.size())[0]
        hidden_size = list(pooled_output.size())[1]
        
        final_output_all = torch.cat((final_output_camimu, cos_pooled_outputs.unsqueeze(1)),1)
        logits_ce = self.classifier(final_output_all)
#         print('logits_ce:')
#         print(logits_ce)
        
#         logits_ori = self.classifier2(final_output_camimu)
#         print('logits_ori:')
#         print(logits_ori)

        #Calculate loss during training process
        if labels is not None:
            if self.num_labels == 1:
                #  We are doing regression
                loss_fct = MSELoss()
                loss = loss_fct(logits.view(-1), labels.view(-1))
            else:
                loss_fct_ce = CrossEntropyLoss()
                loss_ce = loss_fct_ce(logits_ce.view(-1, self.num_labels), labels.view(-1))
                print('loss_ce:')
                print(loss_ce)

#                 loss_ori = loss_fct_ce(logits_ori.view(-1, self.num_labels), labels.view(-1))
#                 print('loss_ori:')
#                 print(loss_ori)
                loss_fct_cos = CosineEmbeddingLoss()

                labels2[labels2==0] = -1
                loss_cos = loss_fct_cos(pooled_output, pooled_output2, labels2)
                labels2[labels2==-1] = 0
                print('loss_cos:')
                print(loss_cos)
            
                loss = loss_ce
                print('final loss:')
                print(loss)
                
#             outputs = (loss,) + outputs
#             outputs = (loss,) + logits_cos 
                outputs = loss
                return outputs
        else:
            #Get predictions when doing evaluation
            return logits_ce
        
          # (loss), logits, (hidden_states), (attentions)


In [6]:
# # Get all of the model's parameters as a list of tuples.
# params = list(model.named_parameters())

# print('The BERT model has {:} different named parameters.\n'.format(len(params)))

# print('==== Embedding Layer ====\n')

# for p in params[0:5]:
#     print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))

# print('\n==== First Transformer ====\n')

# for p in params[5:21]:
#     print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))
    
# print('\n==== Output Layer ====\n')

# for p in params[-4:]:
#     print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))

In [7]:
# data_dir = "D:/Jupyter/data/dataset/perspective_stances/"
# # data_dir = "D:/Projects/Stance/Dataset/OnlyNew/"
# data_dir_output = "D:/Projects/Stance/Models/Consistency_Cues/"
# output_dir=data_dir_output
# max_seq_length=32
# max_grad_norm = 1.0
# num_training_steps = 1000
# num_warmup_steps = 100
# warmup_proportion = float(num_warmup_steps) / float(num_training_steps)  # 0.1
# # warmup_proportion = 0.1
# # train_batch_size=32
# train_batch_size=16
# eval_batch_size=8
# learning_rate=5e-5
# num_train_epochs=4
# local_rank=-1
# seed=19
# gradient_accumulation_steps=1
# loss_scale=128
# train_batch_size = int(train_batch_size / gradient_accumulation_steps)

# processors = {
#         "mrpc": MrpcProcessor,
#     }

# random.seed(seed)
# np.random.seed(seed)
# torch.manual_seed(seed)
# torch.cuda.manual_seed_all(seed)
    
# os.makedirs(output_dir, exist_ok=True)
# processor = processors['mrpc']()
# label_list = processor.get_labels()
# num_labels = len(label_list)
# # print('label list')
# # print(label_list)

# train_examples = processor.get_train_examples(data_dir)
# num_train_steps = int(
#     len(train_examples) / train_batch_size / gradient_accumulation_steps * num_train_epochs)

# ##preprare optimizer
# param_optimizer = list(model.named_parameters())
# no_decay = ['bias', 'gamma', 'beta']
# optimizer_grouped_parameters = [
#     {'params': [p for n, p in param_optimizer if not any(nd in n for nd in no_decay)], 'weight_decay_rate': 0.01},
#     {'params': [p for n, p in param_optimizer if any(nd in n for nd in no_decay)], 'weight_decay_rate': 0.0}
#     ]
# t_total = num_train_steps
# optimizer = BertAdam(optimizer_grouped_parameters,
#                          lr=learning_rate,
#                          warmup=warmup_proportion,
#                          t_total=t_total)
# # optimizer = AdamW(optimizer_grouped_parameters,
# #                   lr = learning_rate, # args.learning_rate - default is 5e-5, our notebook had 2e-5
# #                   eps = 1e-8, # args.adam_epsilon  - default is 1e-8.
# #                   correct_bias=False
# #                 )

# # scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=num_warmup_steps, num_training_steps=t_total)  # PyTorch scheduler

In [8]:
# global_step = 0
# claim_features = convert_claims_to_features(train_examples, label_list, max_seq_length, tokenizer)
# train_features = convert_pers_to_features(train_examples, label_list, max_seq_length, tokenizer)

# logger.info("***** Running training *****")
# logger.info("  Num examples = %d", len(train_examples))
# logger.info("  Batch size = %d", train_batch_size)
# logger.info("  Num steps = %d", num_train_steps)


# all_input_ids = torch.tensor([f.input_ids for f in train_features], dtype=torch.long)
# all_input_mask = torch.tensor([f.input_mask for f in train_features], dtype=torch.long)
# all_segment_ids = torch.tensor([f.segment_ids for f in train_features], dtype=torch.long)
# all_label_ids = torch.tensor([f.label_id for f in train_features], dtype=torch.long)

# claims_input_ids = torch.tensor([f.input_ids for f in claim_features], dtype=torch.long)
# claims_input_mask = torch.tensor([f.input_mask for f in claim_features], dtype=torch.long)
# claims_segment_ids = torch.tensor([f.segment_ids for f in claim_features], dtype=torch.long)
# claims_label_ids = torch.tensor([f.label_id for f in claim_features], dtype=torch.long)

# train_data = TensorDataset(all_input_ids, all_input_mask, all_segment_ids, all_label_ids, claims_input_ids, claims_input_mask, claims_segment_ids, claims_label_ids)
# train_sampler = RandomSampler(train_data)
# train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=train_batch_size)

# # claims_data = TensorDataset(claims_input_ids, claims_input_mask, claims_segment_ids, claims_label_ids)
# # claims_sampler = RandomSampler(claims_data)
# # claims_dataloader = DataLoader(claims_data, sampler=train_sampler, batch_size=train_batch_size)

In [9]:
# model.train()
# for _ in trange(int(num_train_epochs), desc="Epoch"):
#     tr_loss = 0
#     nb_tr_examples, nb_tr_steps = 0, 0
#     for step, batch in enumerate(tqdm(train_dataloader, desc="Iteration")):
#         batch = tuple(t.to(device) for t in batch)
#         input_ids, input_mask, segment_ids, label_ids, claim_input_ids, claim_input_mask, claim_segment_ids, claim_label_ids = batch
# #         ce_loss = model(input_ids, segment_ids, input_mask, label_ids)
# #         cos_loss = model(claim_input_ids, claim_segment_ids, claim_input_mask, claim_label_ids)
        
# #         print("start")
# #         print(input_ids)
# #         print(input_mask)
# #         print(segment_ids)
# #         print(label_ids)
# #         print(claim_input_ids)
# #         print(claim_input_mask)
# #         print(claim_segment_ids)
# #         print(claim_label_ids)
# #         print("end")
    
#         out_results = model(input_ids=input_ids, token_type_ids=segment_ids, attention_mask=input_mask, labels=label_ids, input_ids2=claim_input_ids, token_type_ids2=claim_segment_ids, attention_mask2=claim_input_mask, labels2=claim_label_ids)
# #         loss = ce_loss + cos_loss
#         print("out_results:")
#         print(out_results)
#         loss = out_results
# #         print(cos_loss)
# #         print(loss.item())
#         if n_gpu > 1:
#             loss = loss.mean() # mean() to average on multi-gpu.
# #         if fp16 and loss_scale != 1.0:
# #             # rescale loss for fp16 training
# #             # see https://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html
# #             loss = loss * loss_scale
#         if gradient_accumulation_steps > 1:
#             loss = loss / gradient_accumulation_steps
#         loss.backward()
        
#         tr_loss += loss.item()
#         nb_tr_examples += input_ids.size(0)
#         nb_tr_steps += 1
#         if (step + 1) % gradient_accumulation_steps == 0:
# #             if fp16 or optimize_on_cpu:
# #                 if fp16 and loss_scale != 1.0:
# #                     # scale down gradients for fp16 training
# #                     for param in model.parameters():
# #                         if param.grad is not None:
# #                             param.grad.data = param.grad.data / loss_scale           
# #                 is_nan = set_optimizer_params_grad(param_optimizer, model.named_parameters(), test_nan=True)
# #                 if is_nan:
# #                     logger.info("FP16 TRAINING: Nan in gradients, reducing loss scaling")
# #                     loss_scale = loss_scale / 2
# #                     model.zero_grad()
# #                     continue 
# #                 optimizer.step()
# # #                 scheduler.step()
# #                 copy_optimizer_params_to_model(model.named_parameters(), param_optimizer)
# #             else:
# #                 torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
#             optimizer.step()
# #                 scheduler.step()
#             model.zero_grad()
#             global_step += 1

        
# ## v2: concat
# ## v3: multiply
# model_to_save = model.module if hasattr(model, 'module') else model
# torch.save(model.state_dict(), output_dir + "cosloss_camimu_siamese_bert_epoch4.pth")
# # torch.save(model_to_save.state_dict(), output_dir + "cos_camimu_siamese_bert.bin")

In [16]:
import csv
from pytorch_pretrained_bert.file_utils import PYTORCH_PRETRAINED_BERT_CACHE
def train_and_test(data_dir, bert_model="bert-base-uncased", task_name=None,
                   output_dir=None, max_seq_length=32, do_train=False, do_eval=False, do_lower_case=False,
                   train_batch_size=16, eval_batch_size=8, learning_rate=5e-5, num_train_epochs=5,
                   warmup_proportion=0.1,no_cuda=False, local_rank=-1, seed=19, gradient_accumulation_steps=1,
                   optimize_on_cpu=False, fp16=False, loss_scale=128, saved_model=""):
    


    # ## Required parameters
    # parser.add_argument("--data_dir",
    #                     default=None,
    #                     type=str,
    #                     required=True,
    #                     help="The input data dir. Should contain the .tsv files (or other data files) for the task.")
    # parser.add_argument("--bert_model", default=None, type=str, required=True,
    #                     help="Bert pre-trained model selected in the list: bert-base-uncased, "
    #                          "bert-large-uncased, bert-base-cased, bert-base-multilingual, bert-base-chinese.")
    # parser.add_argument("--task_name",
    #                     default=None,
    #                     type=str,
    #                     required=True,
    #                     help="The name of the task to train.")
    # parser.add_argument("--output_dir",
    #                     default=None,
    #                     type=str,
    #                     required=True,
    #                     help="The output directory where the model checkpoints will be written.")

    ## Other parameters
    # parser.add_argument("--max_seq_length",
    #                     default=128,
    #                     type=int,
    #                     help="The maximum total input sequence length after WordPiece tokenization. \n"
    #                          "Sequences longer than this will be truncated, and sequences shorter \n"
    #                          "than this will be padded.")
    # parser.add_argument("--do_train",
    #                     default=False,
    #                     action='store_true',
    #                     help="Whether to run training.")
    # parser.add_argument("--do_eval",
    #                     default=False,
    #                     action='store_true',
    #                     help="Whether to run eval on the dev set.")
    # parser.add_argument("--do_lower_case",
    #                     default=False,
    #                     action='store_true',
    #                     help="Set this flag if you are using an uncased model.")
    # parser.add_argument("--train_batch_size",
    #                     default=32,
    #                     type=int,
    #                     help="Total batch size for training.")
    # parser.add_argument("--eval_batch_size",
    #                     default=8,
    #                     type=int,
    #                     help="Total batch size for eval.")
    # parser.add_argument("--learning_rate",
    #                     default=5e-5,
    #                     type=float,
    #                     help="The initial learning rate for Adam.")
    # parser.add_argument("--num_train_epochs",
    #                     default=3.0,
    #                     type=float,
    #                     help="Total number of training epochs to perform.")
    # parser.add_argument("--warmup_proportion",
    #                     default=0.1,
    #                     type=float,
    #                     help="Proportion of training to perform linear learning rate warmup for. "
    #                          "E.g., 0.1 = 10%% of training.")
    # parser.add_argument("--no_cuda",
    #                     default=False,
    #                     action='store_true',
    #                     help="Whether not to use CUDA when available")
    # parser.add_argument("--local_rank",
    #                     type=int,
    #                     default=-1,
    #                     help="local_rank for distributed training on gpus")
    # parser.add_argument('--seed',
    #                     type=int,
    #                     default=42,
    #                     help="random seed for initialization")
    # parser.add_argument('--gradient_accumulation_steps',
    #                     type=int,
    #                     default=1,
    #                     help="Number of updates steps to accumulate before performing a backward/update pass.")
    # parser.add_argument('--optimize_on_cpu',
    #                     default=False,
    #                     action='store_true',
    #                     help="Whether to perform optimization and keep the optimizer averages on CPU")
    # parser.add_argument('--fp16',
    #                     default=False,
    #                     action='store_true',
    #                     help="Whether to use 16-bit float precision instead of 32-bit")
    # parser.add_argument('--loss_scale',
    #                     type=float, default=128,
    #                     help='Loss scaling, positive power of 2 values can improve fp16 convergence.')

    # args = parser.parse_args()

    
    processors = {
#         "cola": ColaProcessor,
#         "mnli": MnliProcessor,
        "mrpc": MrpcProcessor,
        "stance":StanceProcessor
    }

    if local_rank == -1 or no_cuda:
        device = torch.device("cuda" if torch.cuda.is_available() and not no_cuda else "cpu")
        n_gpu = torch.cuda.device_count()
    else:
        device = torch.device("cuda", local_rank)
        n_gpu = 1
        # Initializes the distributed backend which will take care of sychronizing nodes/GPUs
        torch.distributed.init_process_group(backend='nccl')
        if fp16:
            logger.info("16-bits training currently not supported in distributed training")
            fp16 = False # (see https://github.com/pytorch/pytorch/pull/13496)
    logger.info("device %s n_gpu %d distributed training %r", device, n_gpu, bool(local_rank != -1))

    if gradient_accumulation_steps < 1:
        raise ValueError("Invalid gradient_accumulation_steps parameter: {}, should be >= 1".format(
                            gradient_accumulation_steps))

    train_batch_size = int(train_batch_size / gradient_accumulation_steps)

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if n_gpu > 0:
        torch.cuda.manual_seed_all(seed)

    if not do_train and not do_eval:
        raise ValueError("At least one of `do_train` or `do_eval` must be True.")

    if do_train:
        if os.path.exists(output_dir) and os.listdir(output_dir):
            raise ValueError("Output directory ({}) already exists and is not emp1ty.".format(output_dir))
        os.makedirs(output_dir, exist_ok=True)

    task_name = task_name.lower()

    if task_name not in processors:
        raise ValueError("Task not found: %s" % (task_name))

    processor = processors[task_name]()
    label_list = processor.get_labels()

#     tokenizer = BertTokenizer.from_pretrained(bert_model, do_lower_case=do_lower_case)
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    

    train_examples = None
    num_train_steps = None
    if do_train:
        train_examples = processor.get_train_examples(data_dir)
        
        num_train_steps = int(
            len(train_examples) / train_batch_size / gradient_accumulation_steps * num_train_epochs)

    # Prepare model
#     model = BertForSequenceClassification.from_pretrained(bert_model,
#                 cache_dir=PYTORCH_PRETRAINED_BERT_CACHE / 'distributed_{}'.format(local_rank), num_labels = 2)

        model = BertForConsistencyCueClassification.from_pretrained('bert-base-uncased', num_labels=2)
        model.to(device)
        
        if fp16:
            model.half()

        if local_rank != -1:
            model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[local_rank],
                                                              output_device=local_rank)
        elif n_gpu > 1:
            model = torch.nn.DataParallel(model)

        # Prepare optimizer
        if fp16:
            param_optimizer = [(n, param.clone().detach().to('cpu').float().requires_grad_()) \
                                for n, param in model.named_parameters()]
        elif optimize_on_cpu:
            param_optimizer = [(n, param.clone().detach().to('cpu').requires_grad_()) \
                                for n, param in model.named_parameters()]
        else:
            param_optimizer = list(model.named_parameters())
        no_decay = ['bias', 'gamma', 'beta']
        optimizer_grouped_parameters = [
            {'params': [p for n, p in param_optimizer if not any(nd in n for nd in no_decay)], 'weight_decay_rate': 0.01},
            {'params': [p for n, p in param_optimizer if any(nd in n for nd in no_decay)], 'weight_decay_rate': 0.0}
            ]
        t_total = num_train_steps
#     print(t_total)
    if local_rank != -1:
        t_total = t_total // torch.distributed.get_world_size()
    if do_train:
        optimizer = BertAdam(optimizer_grouped_parameters,
                         lr=learning_rate,
                         warmup=warmup_proportion,
                         t_total=t_total)

    global_step = 0
    if do_train:
        claim_features = convert_claims_to_features(train_examples, label_list, max_seq_length, tokenizer)
        train_features = convert_pers_to_features(train_examples, label_list, max_seq_length, tokenizer)
        logger.info("***** Running training *****")
        logger.info("  Num examples = %d", len(train_examples))
        logger.info("  Batch size = %d", train_batch_size)
        logger.info("  Num steps = %d", num_train_steps)
        all_input_ids = torch.tensor([f.input_ids for f in train_features], dtype=torch.long)
        all_input_mask = torch.tensor([f.input_mask for f in train_features], dtype=torch.long)
        all_segment_ids = torch.tensor([f.segment_ids for f in train_features], dtype=torch.long)
        all_label_ids = torch.tensor([f.label_id for f in train_features], dtype=torch.long)

        claims_input_ids = torch.tensor([f.input_ids for f in claim_features], dtype=torch.long)
        claims_input_mask = torch.tensor([f.input_mask for f in claim_features], dtype=torch.long)
        claims_segment_ids = torch.tensor([f.segment_ids for f in claim_features], dtype=torch.long)
        claims_label_ids = torch.tensor([f.label_id for f in claim_features], dtype=torch.long)

        train_data = TensorDataset(all_input_ids, all_input_mask, all_segment_ids, all_label_ids, claims_input_ids, claims_input_mask, claims_segment_ids, claims_label_ids)

        if local_rank == -1:
            train_sampler = RandomSampler(train_data)
        else:
            train_sampler = DistributedSampler(train_data)
        train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=train_batch_size)

        model.train()
        for _ in trange(int(num_train_epochs), desc="Epoch"):
            tr_loss = 0
            nb_tr_examples, nb_tr_steps = 0, 0
            for step, batch in enumerate(tqdm(train_dataloader, desc="Iteration")):
                batch = tuple(t.to(device) for t in batch)
                input_ids, input_mask, segment_ids, label_ids, claim_input_ids, claim_input_mask, claim_segment_ids, claim_label_ids = batch
                
                out_results = model(input_ids=input_ids, token_type_ids=segment_ids, attention_mask=input_mask, labels=label_ids, input_ids2=claim_input_ids, token_type_ids2=claim_segment_ids, attention_mask2=claim_input_mask, labels2=claim_label_ids)
#                 loss = model(input_ids, segment_ids, input_mask, label_ids)
                print("out_results:")
                print(out_results)
                loss = out_results
            
                if n_gpu > 1:
                    loss = loss.mean() # mean() to average on multi-gpu.
                if fp16 and loss_scale != 1.0:
                    # rescale loss for fp16 training
                    # see https://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html
                    loss = loss * loss_scale
                if gradient_accumulation_steps > 1:
                    loss = loss / gradient_accumulation_steps
                loss.backward()
                tr_loss += loss.item()
                nb_tr_examples += input_ids.size(0)
                nb_tr_steps += 1
                if (step + 1) % gradient_accumulation_steps == 0:
                    if fp16 or optimize_on_cpu:
                        if fp16 and loss_scale != 1.0:
                            # scale down gradients for fp16 training
                            for param in model.parameters():
                                if param.grad is not None:
                                    param.grad.data = param.grad.data / loss_scale
                        is_nan = set_optimizer_params_grad(param_optimizer, model.named_parameters(), test_nan=True)
                        if is_nan:
                            logger.info("FP16 TRAINING: Nan in gradients, reducing loss scaling")
                            loss_scale = loss_scale / 2
                            model.zero_grad()
                            continue
                        optimizer.step()
                        copy_optimizer_params_to_model(model.named_parameters(), param_optimizer)
                    else:
                        optimizer.step()
                    model.zero_grad()
                    global_step += 1

        torch.save(model.state_dict(), output_dir + "cos_camimu_siamese_bert_epoch5.pth")


    if do_eval and (local_rank == -1 or torch.distributed.get_rank() == 0):
        eval_examples = processor.get_test_examples(data_dir)
#         eval_examples = processor.get_dev_examples(data_dir)
        claim_features = convert_claims_to_features(eval_examples, label_list, max_seq_length, tokenizer)
        eval_features = convert_pers_to_features(
            eval_examples, label_list, max_seq_length, tokenizer)
            
    
        logger.info("***** Running evaluation *****")
        logger.info("  Num examples = %d", len(eval_examples))
        logger.info("  Batch size = %d", eval_batch_size)
        all_input_ids = torch.tensor([f.input_ids for f in eval_features], dtype=torch.long)
        all_input_mask = torch.tensor([f.input_mask for f in eval_features], dtype=torch.long)
        all_segment_ids = torch.tensor([f.segment_ids for f in eval_features], dtype=torch.long)
        all_label_ids = torch.tensor([f.label_id for f in eval_features], dtype=torch.long)
        
        claims_input_ids = torch.tensor([f.input_ids for f in claim_features], dtype=torch.long)
        claims_input_mask = torch.tensor([f.input_mask for f in claim_features], dtype=torch.long)
        claims_segment_ids = torch.tensor([f.segment_ids for f in claim_features], dtype=torch.long)
        claims_label_ids = torch.tensor([f.label_id for f in claim_features], dtype=torch.long)
        
        eval_data = TensorDataset(all_input_ids, all_input_mask, all_segment_ids, all_label_ids, claims_input_ids, claims_input_mask, claims_segment_ids, claims_label_ids)
        # Run prediction for full data
#         eval_sampler = SequentialSampler(eval_data)
        eval_sampler = SequentialSampler(eval_data)
        eval_dataloader = DataLoader(eval_data, sampler=eval_sampler, batch_size=eval_batch_size)
#         print('all_input_ids:')
#         print(all_input_ids)
        
        

#         model.load_state_dict(torch.load(saved_model))
        model_state_dict = torch.load(saved_model)
        model = BertForConsistencyCueClassification.from_pretrained('bert-base-uncased', num_labels=2, state_dict=model_state_dict)
        model.to(device)
        
        model.eval()
        # eval_loss, eval_accuracy = 0, 0

        eval_tp, eval_pred_c, eval_gold_c = 0, 0, 0
        eval_loss, eval_macro_p, eval_macro_r = 0, 0, 0

        raw_score = []

        nb_eval_steps, nb_eval_examples = 0, 0
        for input_ids, input_mask, segment_ids, label_ids, claim_input_ids, claim_input_mask, claim_segment_ids, claim_label_ids in eval_dataloader:
            input_ids = input_ids.to(device)
            input_mask = input_mask.to(device)
            segment_ids = segment_ids.to(device)
            label_ids = label_ids.to(device)
            claim_input_ids = claim_input_ids.to(device)
            claim_input_mask = claim_input_mask.to(device)
            claim_segment_ids = claim_segment_ids.to(device)
            claim_label_ids = claim_label_ids.to(device)

#             print("start")
#             print(input_ids)
#             print(input_mask)
#             print(segment_ids)
#             print(label_ids)
#             print(claim_input_ids)
#             print(claim_input_mask)
#             print(claim_segment_ids)
#             print(claim_label_ids)
#             print("end")
            with torch.no_grad():
                tmp_eval_loss = model(input_ids=input_ids, token_type_ids=segment_ids, attention_mask=input_mask, labels=label_ids, input_ids2=claim_input_ids, token_type_ids2=claim_segment_ids, attention_mask2=claim_input_mask, labels2=claim_label_ids)
                
                logits = model(input_ids=input_ids, token_type_ids=segment_ids, attention_mask=input_mask, input_ids2=claim_input_ids, token_type_ids2=claim_segment_ids, attention_mask2=claim_input_mask)
            
            print(logits)
#             print(logits[0])
            logits = logits.detach().cpu().numpy()
            print(logits)
            label_ids = label_ids.to('cpu').numpy()
#             print(label_ids)

            # Micro F1 (aggregated tp, fp, fn counts across all examples)
            tmp_tp, tmp_pred_c, tmp_gold_c = tp_pcount_gcount(logits, label_ids)
            eval_tp += tmp_tp
            eval_pred_c += tmp_pred_c
            eval_gold_c += tmp_gold_c
            
            pred_label = np.argmax(logits, axis=1)
            raw_score += zip(logits, pred_label, label_ids)
            
            # Macro F1 (averaged P, R across mini batches)
            tmp_eval_p, tmp_eval_r, tmp_eval_f1 = p_r_f1(logits, label_ids)

            eval_macro_p += tmp_eval_p
            eval_macro_r += tmp_eval_r

            eval_loss += tmp_eval_loss.mean().item()
            nb_eval_examples += input_ids.size(0)
            nb_eval_steps += 1


        # Micro F1 (aggregated tp, fp, fn counts across all examples)
        eval_micro_p = eval_tp / eval_pred_c
        eval_micro_r = eval_tp / eval_gold_c
        eval_micro_f1 = 2 * eval_micro_p * eval_micro_r / (eval_micro_p + eval_micro_r)

        # Macro F1 (averaged P, R across mini batches)
        eval_macro_p = eval_macro_p / nb_eval_steps
        eval_macro_r = eval_macro_r / nb_eval_steps
        eval_macro_f1 = 2 * eval_macro_p * eval_macro_r / (eval_macro_p + eval_macro_r)

        eval_loss = eval_loss / nb_eval_steps
        result = {
                  'eval_loss': eval_loss,
                  'eval_micro_p': eval_micro_p,
                  'eval_micro_r': eval_micro_r,
                  'eval_micro_f1': eval_micro_f1,
                  'eval_macro_p': eval_macro_p,
                  'eval_macro_r': eval_macro_r,
                  'eval_macro_f1': eval_macro_f1,
#                   'global_step': global_step,
#                   'loss': tr_loss/nb_tr_steps
                  }

        output_eval_file = os.path.join(output_dir, "ibmcstrain_cos_camimu_siamese_bert_epoch5_siamese_bert_test_eval_results.txt")
        output_raw_score = os.path.join(output_dir, "ibmcstrain_cos_camimu_siamese_bert_epoch5_siamese_bert_test_raw_score.csv")
        with open(output_eval_file, "w") as writer:
            logger.info("***** Eval results *****")
            for key in sorted(result.keys()):
                logger.info("  %s = %s", key, str(result[key]))
                writer.write("%s = %s\n" % (key, str(result[key])))

        with open(output_raw_score, 'w') as fout:
            fields = ["undermine_score", "support_score","predict_label", "gold"]
            writer = csv.DictWriter(fout, fieldnames=fields)
            writer.writeheader()
            for score, pred, gold in raw_score:
                writer.writerow({
                    "undermine_score": str(score[0]),
                    "support_score": str(score[1]),
                    "predict_label": str(pred),
                    "gold": str(gold)
                })

In [11]:
def experiments():
    data_dir = "D:/Jupyter/data/dataset/perspective_stances/"
    
    data_dir_output = "D:/Projects/Stance/Models/Siamese_bert/"
    train_and_test(data_dir=data_dir, do_train=True, do_eval=False, output_dir=data_dir_output,task_name="stance")


In [17]:
def evaluation_with_pretrained():
    bert_model = "D:/Projects/Stance/Models/Siamese_bert/cos_camimu_siamese_bert_epoch5.pth"
#     bert_model = "D:/Projects/Stance/Models/Consistency_Cues/cosloss_camimu_siamese_bert_epoch4.pth"
#     data_dir = "D:/Jupyter/data/dataset/perspective_stances/"
    data_dir = "D:/Jupyter/data/dataset/ibmcs/"

    
    data_dir_output = "D:/Projects/Stance/Evaluation/local_output/"
    train_and_test(data_dir=data_dir, do_train=False, do_eval=True, output_dir=data_dir_output,task_name="stance",saved_model=bert_model)

In [18]:
if __name__ == "__main__":
#     experiments()
    evaluation_with_pretrained()

06/18/2020 13:14:04 - INFO - run_classifier -   device cuda n_gpu 1 distributed training False
06/18/2020 13:14:06 - INFO - transformers.tokenization_utils -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at C:\Users\arsen\.cache\torch\transformers\26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
06/18/2020 13:14:06 - INFO - run_classifier -   *** Claim Example ***
06/18/2020 13:14:06 - INFO - run_classifier -   guid: test-1
06/18/2020 13:14:06 - INFO - run_classifier -   tokens: [CLS] this house believes that open primaries are the most effective method of selecting candidates for elections [SEP]
06/18/2020 13:14:06 - INFO - run_classifier -   input_ids: 101 2023 2160 7164 2008 2330 27419 2024 1996 2087 4621 4118 1997 17739 5347 2005 3864 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0
06/18/2020 13:14:06 - INFO - run_classifier -   input_mask: 1 1 1 1 1 1 1 1 1 

['Label', 'x', 'y', 'claim', 'perspective']
['0', '0', '0', 'This house believes that open primaries are the most effective method of selecting candidates for elections', 'A single election in which the party nominee is selected by nonparty members could be enough to destroy the party']
['0', '0', '0', 'This house believes that open primaries are the most effective method of selecting candidates for elections', "A party's basic function is to choose its own leaders"]
['1', '0', '0', 'This house believes that open primaries are the most effective method of selecting candidates for elections', 'The open primary can be seen as good for voter participation']
['1', '0', '0', 'This house believes that open primaries are the most effective method of selecting candidates for elections', 'the open primary allows nonpartisan or independent voters to participate in the nominating process']
['1', '0', '0', 'This house believes that open primaries are the most effective method of selecting candidat

06/18/2020 13:14:06 - INFO - run_classifier -   *** Perspective Example ***
06/18/2020 13:14:06 - INFO - run_classifier -   guid: test-1
06/18/2020 13:14:06 - INFO - run_classifier -   tokens: [CLS] a single election in which the party nominee is selected by non ##par ##ty members could be enough to destroy the party [SEP]
06/18/2020 13:14:06 - INFO - run_classifier -   input_ids: 101 1037 2309 2602 1999 2029 1996 2283 9773 2003 3479 2011 2512 19362 3723 2372 2071 2022 2438 2000 6033 1996 2283 102 0 0 0 0 0 0 0 0
06/18/2020 13:14:06 - INFO - run_classifier -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0
06/18/2020 13:14:06 - INFO - run_classifier -   segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
06/18/2020 13:14:06 - INFO - run_classifier -   label: 0 (id = 0)
06/18/2020 13:14:06 - INFO - run_classifier -   *** Perspective Example ***
06/18/2020 13:14:06 - INFO - run_classifier -   guid: test-2
06/18/2020 13:14:06 - INFO - 

loss_ce:
tensor(3.3624, device='cuda:0')
loss_cos:
tensor(0.3203, device='cuda:0')
final loss:
tensor(3.3624, device='cuda:0')
tensor([[ 9.4343, -8.7196],
        [-0.9156,  2.1019],
        [-6.3652,  7.4732],
        [-5.1950,  6.1040],
        [-5.6665,  6.6259],
        [-5.1726,  6.0016],
        [-5.8035,  6.8565],
        [ 8.9920, -8.1587]], device='cuda:0')
[[ 9.434318   -8.719608  ]
 [-0.91559607  2.1018636 ]
 [-6.365227    7.4732385 ]
 [-5.1950336   6.104032  ]
 [-5.6664968   6.625898  ]
 [-5.172606    6.0016446 ]
 [-5.803538    6.856486  ]
 [ 8.9919615  -8.158745  ]]
loss_ce:
tensor(1.1104, device='cuda:0')
loss_cos:
tensor(0.2046, device='cuda:0')
final loss:
tensor(1.1104, device='cuda:0')
tensor([[ 9.4323, -8.6695],
        [ 9.5901, -8.9373],
        [ 8.7493, -8.2605],
        [ 8.8268, -8.2167],
        [-3.3375,  4.3989],
        [-0.0187,  0.6023],
        [-1.3902,  1.0066],
        [-2.3480,  2.4348]], device='cuda:0')
[[ 9.432296   -8.669501  ]
 [ 9.590119   -8.9

loss_ce:
tensor(0.3954, device='cuda:0')
loss_cos:
tensor(0.2181, device='cuda:0')
final loss:
tensor(0.3954, device='cuda:0')
tensor([[-3.5029,  3.2786],
        [-2.3287,  2.1978],
        [-3.8927,  3.5711],
        [-1.2594,  1.3503],
        [-4.0570,  4.1878],
        [ 0.6420, -0.1294],
        [-3.2805,  3.4922],
        [-1.2963,  1.0804]], device='cuda:0')
[[-3.5029385   3.278608  ]
 [-2.3286638   2.1978326 ]
 [-3.8926537   3.5710828 ]
 [-1.2594365   1.3502911 ]
 [-4.0570483   4.1878467 ]
 [ 0.64197296 -0.12935318]
 [-3.280547    3.4922068 ]
 [-1.2963127   1.0803849 ]]
loss_ce:
tensor(1.3502, device='cuda:0')
loss_cos:
tensor(0.4884, device='cuda:0')
final loss:
tensor(1.3502, device='cuda:0')
tensor([[-3.0017,  2.8564],
        [ 0.1527, -0.5750],
        [-0.2055, -0.0408],
        [ 2.0309, -1.4746],
        [-0.1405, -0.0876],
        [ 0.4323, -0.2027],
        [ 3.5726, -3.0346],
        [ 0.1387,  0.1304]], device='cuda:0')
[[-3.0017135   2.856383  ]
 [ 0.15269658 -0.5

tensor([[ 10.6048, -10.0362],
        [  8.3074,  -7.3756],
        [  7.6107,  -6.4309],
        [  3.0310,  -1.5518],
        [  8.7007,  -7.8832],
        [ -5.2776,   6.5271],
        [ -2.6457,   3.7083],
        [ -5.2268,   6.7564]], device='cuda:0')
[[ 10.6047735 -10.036233 ]
 [  8.307403   -7.3756404]
 [  7.6106644  -6.4309297]
 [  3.0309632  -1.5518204]
 [  8.700732   -7.8831816]
 [ -5.277559    6.5270534]
 [ -2.645715    3.7083366]
 [ -5.2267666   6.756449 ]]
loss_ce:
tensor(1.1886, device='cuda:0')
loss_cos:
tensor(0.2110, device='cuda:0')
final loss:
tensor(1.1886, device='cuda:0')
tensor([[ 7.2804, -6.2501],
        [ 9.0118, -8.1431],
        [-2.7945,  4.0668],
        [10.1009, -9.3304],
        [ 5.3835, -4.1239],
        [-5.3116,  6.4578],
        [-4.8697,  6.3170],
        [ 6.5206, -5.2979]], device='cuda:0')
[[ 7.280367  -6.2501254]
 [ 9.011811  -8.143073 ]
 [-2.794472   4.0668464]
 [10.100855  -9.330381 ]
 [ 5.3834825 -4.123893 ]
 [-5.31157    6.4577794]
 [-4.8

tensor([[ 4.4801, -3.3374],
        [-4.2035,  5.3211],
        [ 3.8230, -2.5894],
        [10.3183, -9.6528],
        [-3.5743,  3.9005],
        [-2.5746,  2.5441],
        [ 1.6382, -1.3336],
        [-4.4832,  4.3929]], device='cuda:0')
[[ 4.4800544 -3.337421 ]
 [-4.2035346  5.321139 ]
 [ 3.8229895 -2.5894058]
 [10.318297  -9.652761 ]
 [-3.5743413  3.900469 ]
 [-2.5746367  2.5441363]
 [ 1.6381866 -1.3336095]
 [-4.4831796  4.3928695]]
loss_ce:
tensor(0.3051, device='cuda:0')
loss_cos:
tensor(0.2273, device='cuda:0')
final loss:
tensor(0.3051, device='cuda:0')
tensor([[ 0.8730, -0.2746],
        [-0.6793,  0.8468],
        [-0.8827,  0.8656],
        [ 5.6157, -4.9038],
        [ 2.2342, -1.6734],
        [ 2.5132, -1.8879],
        [-3.0476,  3.1022],
        [ 0.9671, -0.6203]], device='cuda:0')
[[ 0.8730195  -0.27459997]
 [-0.6792991   0.84684926]
 [-0.88266295  0.8655676 ]
 [ 5.615687   -4.9037814 ]
 [ 2.2341654  -1.6734287 ]
 [ 2.5131776  -1.8878984 ]
 [-3.0476472   3.1021593 ]

tensor([[-4.9065,  5.1611],
        [-4.7731,  4.8977],
        [-4.0104,  4.3867],
        [-4.5282,  4.7987],
        [ 3.5154, -2.5211],
        [-0.9544,  1.4905],
        [-3.5544,  3.7835],
        [-3.0476,  3.4209]], device='cuda:0')
[[-4.906519    5.1611314 ]
 [-4.773102    4.897736  ]
 [-4.010424    4.386658  ]
 [-4.528176    4.798661  ]
 [ 3.515412   -2.5210526 ]
 [-0.95435023  1.4904811 ]
 [-3.5544302   3.783514  ]
 [-3.04763     3.4208574 ]]
loss_ce:
tensor(1.3773, device='cuda:0')
loss_cos:
tensor(0.2238, device='cuda:0')
final loss:
tensor(1.3773, device='cuda:0')
tensor([[-3.6910,  4.0512],
        [-0.9022,  1.3987],
        [ 6.0822, -5.1943],
        [ 1.7637, -1.4211],
        [-3.1824,  3.1205],
        [-1.0526,  1.1074],
        [ 3.5459, -3.3526],
        [ 2.6830, -2.4244]], device='cuda:0')
[[-3.6910121  4.0511703]
 [-0.902165   1.3986855]
 [ 6.0821733 -5.194308 ]
 [ 1.763683  -1.4210935]
 [-3.1824152  3.1205025]
 [-1.0525807  1.1073989]
 [ 3.5458984 -3.352571

tensor([[-0.3235,  0.2954],
        [ 0.7359, -1.0131],
        [ 1.6745, -1.2953],
        [ 4.0960, -3.3375],
        [ 0.9098, -0.3975],
        [-2.9658,  2.5760],
        [ 1.1649, -0.6838],
        [ 0.9796, -0.5174]], device='cuda:0')
[[-0.32346714  0.29536813]
 [ 0.7359299  -1.0130974 ]
 [ 1.6745007  -1.2952617 ]
 [ 4.0960107  -3.3374794 ]
 [ 0.90977937 -0.39750272]
 [-2.9658034   2.5759532 ]
 [ 1.1648791  -0.6838102 ]
 [ 0.97956717 -0.51736945]]
loss_ce:
tensor(3.3132, device='cuda:0')
loss_cos:
tensor(0.7670, device='cuda:0')
final loss:
tensor(3.3132, device='cuda:0')
tensor([[ 4.3773, -3.5318],
        [-0.3667,  0.2890],
        [-4.8557,  4.4121],
        [ 3.2159, -2.5753],
        [ 4.0802, -3.3496],
        [-1.3907,  1.2309],
        [-3.3298,  3.1239],
        [-0.6529,  0.6270]], device='cuda:0')
[[ 4.377313   -3.5317745 ]
 [-0.36671376  0.28903776]
 [-4.8557014   4.4120526 ]
 [ 3.2158759  -2.5753026 ]
 [ 4.080202   -3.3496044 ]
 [-1.3907405   1.2309428 ]
 [-3.32984

tensor([[-4.2129,  3.7343],
        [ 3.1763, -2.9350],
        [-3.0911,  2.7469],
        [-0.1080,  0.3442],
        [ 2.3460, -1.6984],
        [ 2.7508, -2.3558],
        [-1.8119,  1.5680],
        [ 2.2316, -1.9121]], device='cuda:0')
[[-4.212949    3.7342918 ]
 [ 3.1763163  -2.935022  ]
 [-3.0910935   2.7468953 ]
 [-0.10799104  0.34416676]
 [ 2.3460395  -1.6983889 ]
 [ 2.7507908  -2.355799  ]
 [-1.811912    1.5679989 ]
 [ 2.2316291  -1.9120955 ]]
loss_ce:
tensor(2.9279, device='cuda:0')
loss_cos:
tensor(0.4479, device='cuda:0')
final loss:
tensor(2.9279, device='cuda:0')
tensor([[-5.1147,  4.6891],
        [ 1.1684, -1.0280],
        [-1.9600,  1.7359],
        [-3.3327,  2.9264],
        [ 3.4904, -2.6671],
        [ 3.2749, -2.4921],
        [ 3.9138, -3.2711],
        [ 0.4315, -0.5919]], device='cuda:0')
[[-5.1146684   4.689066  ]
 [ 1.168417   -1.0280246 ]
 [-1.9600329   1.7359158 ]
 [-3.332686    2.9263918 ]
 [ 3.4904385  -2.6671226 ]
 [ 3.2748675  -2.4920704 ]
 [ 3.91381

tensor([[-2.2672,  2.5568],
        [-2.3997,  2.9950],
        [-0.3714,  0.0216],
        [ 0.5985,  0.3068],
        [-1.3738,  2.6552],
        [-2.1906,  2.4004],
        [-1.1686,  1.2747],
        [-2.2747,  2.6721]], device='cuda:0')
[[-2.2671752   2.556771  ]
 [-2.3997147   2.9949954 ]
 [-0.37136826  0.02157019]
 [ 0.59853286  0.3068222 ]
 [-1.3737651   2.655194  ]
 [-2.1906104   2.400442  ]
 [-1.1685897   1.2746633 ]
 [-2.2747288   2.6720846 ]]
loss_ce:
tensor(2.5197, device='cuda:0')
loss_cos:
tensor(0.4262, device='cuda:0')
final loss:
tensor(2.5197, device='cuda:0')
tensor([[ 0.5222,  0.6593],
        [-1.8080,  1.9914],
        [-3.8549,  4.0643],
        [-3.3653,  3.7130],
        [-0.8279,  0.7405],
        [-3.2271,  3.4827],
        [-1.7150,  2.0267],
        [ 7.6543, -7.1979]], device='cuda:0')
[[ 0.5221793   0.659308  ]
 [-1.808009    1.9914327 ]
 [-3.8549244   4.06427   ]
 [-3.3652568   3.7129643 ]
 [-0.82790273  0.7405315 ]
 [-3.2271323   3.4826946 ]
 [-1.71502

[[-3.8039434  4.3638544]
 [-5.6992126  6.351702 ]
 [-3.220048   3.5107899]
 [-6.017671   6.6746325]
 [-4.856489   5.463983 ]
 [ 8.033946  -7.2015924]
 [ 2.521667  -1.5697018]
 [ 5.701798  -4.8883224]]
loss_ce:
tensor(0.9950, device='cuda:0')
loss_cos:
tensor(0.2199, device='cuda:0')
final loss:
tensor(0.9950, device='cuda:0')
tensor([[ -5.2509,   5.8488],
        [ -0.8191,   1.0203],
        [  1.8953,  -1.2033],
        [ -0.2327,   0.6675],
        [ 11.0020, -10.4454],
        [ -4.7109,   5.8529],
        [ -2.4408,   3.4808],
        [  0.4550,   0.2651]], device='cuda:0')
[[ -5.250876     5.848763  ]
 [ -0.81905824   1.0202872 ]
 [  1.8952521   -1.2033299 ]
 [ -0.23269722   0.6674687 ]
 [ 11.002022   -10.445395  ]
 [ -4.7109275    5.852895  ]
 [ -2.4407876    3.4807851 ]
 [  0.45497274   0.26513064]]
loss_ce:
tensor(1.0406, device='cuda:0')
loss_cos:
tensor(0.1071, device='cuda:0')
final loss:
tensor(1.0406, device='cuda:0')
tensor([[ 3.2243, -2.2808],
        [ 4.5301, -3.5746]

06/18/2020 13:15:13 - INFO - run_classifier -   ***** Eval results *****
06/18/2020 13:15:13 - INFO - run_classifier -     eval_loss = 1.5135932779656007
06/18/2020 13:15:13 - INFO - run_classifier -     eval_macro_f1 = 0.7207747704668732
06/18/2020 13:15:13 - INFO - run_classifier -     eval_macro_p = 0.7495787545787543
06/18/2020 13:15:13 - INFO - run_classifier -     eval_macro_r = 0.6941025641025641
06/18/2020 13:15:13 - INFO - run_classifier -     eval_micro_f1 = 0.719327731092437
06/18/2020 13:15:13 - INFO - run_classifier -     eval_micro_p = 0.7575221238938054
06/18/2020 13:15:13 - INFO - run_classifier -     eval_micro_r = 0.6848


tensor([[-1.6925,  2.4440],
        [ 2.2862, -1.3692],
        [ 3.3728, -2.4149],
        [-1.0045,  1.3828],
        [ 1.2033, -0.2484],
        [ 0.0797,  0.4030],
        [ 1.4267, -1.0833]], device='cuda:0')
[[-1.6924509   2.443971  ]
 [ 2.2861583  -1.3691804 ]
 [ 3.3728273  -2.414909  ]
 [-1.0045      1.3827695 ]
 [ 1.2032619  -0.24841821]
 [ 0.07971662  0.40296867]
 [ 1.4266807  -1.0832504 ]]
